version: "3.9"

services:
  keycloak:
    image: jboss/keycloak:12.0.2
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: database
      DB_VENDOR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    depends_on:
      - database
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: keycloak
      TZ: Asia/Tokyo
    networks:
      keycloak:
  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
    depends_on:
      - database
    networks:
      keycloak:
  apisix:
    image: apache/apisix:2.2-alpine
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    depends_on:
      - etcd
      - backend-1
      - backend-2
    restart: always
    networks:
      keycloak:
        aliases:
          - apisix.localtest.me
  apisix-dashboard:
    image: apache/apisix-dashboard:2.3
    ports:
      - "9000:9000"
    volumes:
      - ./apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
      - ./apisix-dashboard_log:/usr/local/apisix-dashboard/logs
    depends_on:
      - apisix
      - etcd
    restart: always
    networks:
      keycloak:
        aliases:
          - apisix-dashboard.localtest.me
  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      keycloak:
  backend-1:
    image: nginx
    ports:
      - 10080:80
    volumes:
      - ./html/1:/usr/share/nginx/html
    networks:
      keycloak:
        aliases:
          - backend-1.localtest.me
  backend-2:
    image: nginx
    ports:
      - 10081:80
    volumes:
      - ./html/2:/usr/share/nginx/html
    networks:
      keycloak:
        aliases:
          - backend-2.localtest.me

networks:
  keycloak:
