version: "3"

services:
  digdag:
    build: .
    image: digdag:example
  digdag-server:
    image: digdag:example
    volumes:
      - ./bin/digdag-server-run.sh:/usr/local/bin/digdag-server.sh
    ports:
      - 65432:65432
    entrypoint: [sh, /usr/local/bin/digdag-server.sh]
