version: "3.8"

services:
  openresty:
    image: openresty/openresty:1.19.3.1-buster-fat
    environment:
      NGINX_HOST: openresty.localtest.me
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./data:/data
    ports:
      - 80:80
